path:
    raw_enc : '../data/tokenized/train.en'
    raw_dec : '../data/tokenized/train.en'

    out_dir : '../result/lstm_100'

param:
    n_epoch     : 100
    size_batch  : 100
    size_embed  : 300
    size_hidden : 150
